---
title: "Problema 1 - Checkpoint 4 - Relatório Final"
output:
  html_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
  warning = FALSE,
  message = FALSE,
  screenshot.force = FALSE,
  fig.cap = '',
  fig.align = 'center',
  fig.width = 10)
```

```{r}
library(tidyr)
library(dplyr)
library(readr)
library(ggplot2)

theme_set(theme_minimal())
```


```{r}
series <- read_csv("series_from_imdb.csv")
```


## O episódios _season finale_ são considerados melhores que os demais?  
```{r}

season_finale_eps <- series %>%
  group_by(series_name, season) %>%
  summarise(season_ep = max(season_ep))

season_finale_eps$is.finale <- TRUE

series <- right_join(season_finale_eps, series, by = c("series_name", "season", "season_ep"))

series$is.finale <- ifelse(is.na(series$is.finale), FALSE, TRUE)

ggplot(series, aes(x = is.finale, y = UserRating)) +
  geom_boxplot(outlier.shape = NA)

median(filter(series, is.finale)$UserRating)
median(filter(series, !is.finale)$UserRating)

mean(filter(series, is.finale)$UserRating)
mean(filter(series, !is.finale)$UserRating)

# Escolher as series usadas na analise anterior!!
# O episódio final de cada temporada influencia significativamente no desempenho da série?
sub_series <- filter(series, series_name %in% c("Agents of S.H.I.E.L.D.", "House of Cards", "Orphan Black", "The 100", "The Blacklist", "Vikings"))

ggplot(sub_series, aes(x = series_ep, y = UserRating, color = series_name)) +
  geom_line() +
  geom_point(data = filter(sub_series, is.finale), aes(color = series_name)) +
  facet_wrap(~series_name, scales = "free_x", ncol = 2)
```


## Séries com muitos episódios tendem a ser melhor avaliadas ao longo do tempo? 
```{r}
series_longas <- series %>%
  group_by(series_name) %>%
  summarise(eps = max(series_ep)) %>%
  filter(eps >= 100)

data_series_longas <- filter(series, series_name %in% c(series_longas$series_name))

ggplot(data_series_longas, aes(x = series_ep, y = UserRating, color = series_name)) +
  geom_line() +
  facet_wrap(~series_name, scales = "free_x", ncol = 2)

ggplot(data_series_longas, aes(x = series_ep, y = UserRating, color = series_name)) +
  geom_smooth() +
  facet_wrap(~series_name, scales = "free_x", ncol = 2)

```

