---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.align="center")

library(tidyverse)
library(resample)
library(GGally)
library(knitr)
library(lubridate)
library(chron)
library(highcharter)
library(xts)

theme_set(theme_bw())
```


```{r}
dados <- read.csv("github-users-committing-filetypes.csv")

dados <- dados %>%
  unite("data", the_year, the_month, month_day, sep = "-") %>%
  mutate(data = as.Date(strptime(data, "%Y-%m-%d"))) %>%
  mutate(fds = is.weekend(data)) %>%
  mutate(dia_da_semana = weekdays(data)) %>%
  mutate(mes = month(data)) %>%
  mutate(is_segsex = dia_da_semana %in% c("segunda", "sexta"))
```

```{r}
dados_ <- dados %>%
  select(-c(file_extension, fds, dia_da_semana)) %>%
  group_by(data) %>%
  summarise(users_tot = sum(users)) %>%
  remove_rownames %>% 
  column_to_rownames(var="data") %>%
  as.xts()

highchart(type = "stock") %>% 
  hc_title(text = "Timeline da Atividade Geral do Github") %>%
  hc_add_series(dados_)

monthplot(dados_)
```


```{r}
dados.group <- dados %>%
  filter(substr(data, 0,  4) == "2016") %>%
  group_by(mes = substr(data, 6,  7), dia = substr(data, 9,  10)) %>%
  summarize(usuarios = sum(users)) %>%
  group_by(mes) %>%
  summarise(usuarios.median = median(usuarios))

ggplot(data = dados.group, aes(x = mes, y = usuarios.median)) +
  geom_line() +
  geom_point()

dados.group2 <- dados %>%
  filter(substr(data, 0,  4) == "2017") %>%
  group_by(mes) %>%
  summarize(mediana = median(users),
            media = mean(users))

ggplot(data = dados.group2, aes(x = mes, y = mediana)) +
  geom_line() +
  geom_point() +
  scale_x_discrete()

dados.meses <- dados %>%
  filter(mes %in% c(1, 12))
dados.ferias <- dados %>%
  filter(!(mes %in% c(1, 12)))



dados_diff <- bootstrap2(data = dados.meses$users,
                      data2 = dados.ferias$users,
                      median,
                      R = 10000)
dados_diff.ci <- CI.percentile(dados_diff, probs = c(.025, .975))
dados_diff.ci

data.frame(dados_diff.ci) %>% 
  ggplot(aes(x = "Diferença", ymin = X2.5., ymax = X97.5.)) + 
  geom_errorbar(width = .2) + 
  geom_hline(yintercept = 0, colour = "darkblue")
```

```{r}

median.md <- bootstrap2(dados_md$users,
                        treatment = dados_md$fds,
                        median,
                        R = 10000)

median.md.diff <- CI.percentile(median.md, probs = c(.025, .975))

data.frame(median.md.diff) %>% 
  ggplot(aes(x = "Diferença", ymin = X2.5., ymax = X97.5.)) + 
  geom_errorbar(width = .2) + 
  geom_hline(yintercept = 0, colour = "darkblue")
```


```{r}
dados_m <- dados %>%
  select(-c(file_extension, dia_da_semana)) %>%
  remove_rownames %>% 
  column_to_rownames(var="data") %>%
  as.xts()

highchart(type = "stock") %>% 
  hc_title(text = "Timeline da Atividade de JavaScript") %>%
  hc_add_series(dados_m)
```


# Perguntas

## Existe diferença significativa na mediana da popularidade de quaisquer 2 linguagens entre o período de férias e os meses de trabalho do ano?

## Existe diferença na produtividade dos programadores nos dias próximos ao fim de semana (segunda e sexta) e os do meio da semana (terça, quarta e quinta)?

```{r}
dados.ss = bootstrap(dados %>%
                filter(is_segsex), median(users))

ss.CI = CI.bca(dados.ss, probs = c(.025, .975))
ss.CI

dados.Nss = bootstrap(dados %>%
                filter(!is_segsex), median(users))

Nss.CI = CI.bca(dados.Nss, probs = c(.025, .975))
Nss.CI

df <- data.frame(rbind(ss.CI,
                       Nss.CI))

df$medida = row.names(df)

df %>% 
  ggplot(aes(x = medida, ymin = X2.5., ymax = X97.5.)) + 
  geom_errorbar(width = .2)



mSS <- bootstrap2(dados$users,
                  treatment = dados$is_segsex,
                  median,
                  R = 10000)
mSS.CI <- CI.percentile(mSS, probs = c(.025, .975))

data.frame(mSS.CI) %>%
  ggplot(aes(x = "Diferença", ymin = X2.5., ymax = X97.5.)) + 
  geom_errorbar(width = .2) + 
  geom_hline(yintercept = 0, colour = "darkblue")

```


